app/urls.py
from django.urls import path
from . import views

app_name = 'app'

urlpatterns = [
    path('', views.data, name='data'),
    path('graph/', views.graph, name='graph'),
]

ubp/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('app/', include('app.urls', namespace='app'))
]

app/models.py
from django.db import models

# Create your models here.

app/forms.py
from django import forms

class MyForm(forms.Form):
    start = forms.CharField(max_length=20)
    wait = forms.IntegerField()
    amount = forms.FloatField()
    base = forms.CharField(max_length=3)
    target = forms.CharField(max_length=3)

app/views.py
from django.shortcuts import render
from .forms import MyForm
import requests as r
from statsmodels.tsa.arima_model import ARIMA
import pandas as pd
import numpy as np
import plotly.offline as pyo
import plotly.graph_objs as go
import datetime


def data_get(start, base, target):
    start = datetime.datetime.strptime(start, '%Y-%m-%d')
    start_ = (start - datetime.timedelta(days=60)).strftime('%Y-%m-%d')
    url = 'https://api.exchangeratesapi.io/history?start_at='+str(start_)+'&end_at='+str((start- datetime.timedelta(days=1)).strftime('%Y-%m-%d'))+'&base='+str(base.upper())+'&symbols='+str(target.upper())
    res = r.get(url)
    d = res.json()
    df = pd.DataFrame()
    for i in sorted(d['rates']):
        df = df.append([[i, d['rates'][i][target.upper()]]], ignore_index=True)
    df.columns = ['Date', str('Rate(in '+target.upper()+')')]
    df.to_csv('data.csv', index=False)


def predict(request, amount, wait):
    # dataset
    df = pd.read_csv('data.csv')
    # fit model
    model = ARIMA(np.asarray(df[df.columns[1]], dtype='float'), order=(3, 1, 2))
    model_fit = model.fit(disp=False)
    # make prediction
    yhat = model_fit.predict(len(df[df.columns[1]]), len(df[df.columns[1]]) + wait, typ='levels')
    # print(yhat)

    datelist = pd.date_range(pd.datetime.strptime(df['Date'][len(df['Date'])-1], '%Y-%m-%d'), periods=wait+1).tolist()
    x_date = [i.strftime('%Y-%m-%d') for i in datelist]
    fin_amt = [amount * i for i in yhat]
    graph = go.Scatter(
        x=x_date,
        y=fin_amt,
        mode='lines+markers',
        name='value'
    )

    pyo.plot([graph], filename='graph.html', auto_open=False)
    d={}
    for i in range(len(yhat)):
        d[x_date[i]] = yhat[i]

    return d


def graph(request):
    return render(request, 'graph.html')


def data(request):
    if request.method == "POST":
        m = MyForm(request.POST)
        if m.is_valid():
            start = m.cleaned_data['start']
            wait = m.cleaned_data['wait']
            amount = m.cleaned_data['amount']
            base = m.cleaned_data['base']
            target = m.cleaned_data['target']

            data_get(start, base, target)
            d = predict(request, amount, wait)
            return render(request, 'app/res.html', {'d': d})

    else:
        m = MyForm()
    return render(request, 'app/index.html', {'form': m})

app/templates/app/index.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Sample</title>
    <link rel="icon" href="data:,">
    <style>
        div{
            border: 2px solid black;
            border-radius: 7px;
            padding: 35px 5px 35px 5px;
            width: 50%;
            margin: 0 auto;
        }
        input{
            height: 17px;
            width: 170px;
            border: 1px solid gray;
            border-radius: 5px;
        }
        input[type=submit]{
            background-color: rgba(200,200,200,0.8);
            height: 22px;
            width: 140px;
            font-weight: 700;
        }
        span{
            font-size: 11px;
        }
    </style>
</head>
<body>
    <marquee><h2>Exchange Rate Forecasting</h2></marquee>
    <div align="center">
        <form name="form" action="{% url 'app:data' %}" method = "post">
            {% csrf_token %}
            <input type="text" name = "start" placeholder=" Start Date"><br><span>(yyyy-mm-dd)</span><br><br>
            <input type="text" name = "wait" placeholder=" Waiting time"><br><span>(no. of days)</span><br><br>
            <input type="text" name = "amount" placeholder=" Amount"><br><br><br>
            <input type="text" name = "base" placeholder=" Base Currency">&nbsp;<br><span>(eg:USD,INR,AUD,...)</span><br><br>
            <input type="text" name = "target" placeholder=" Target Currency"><br><span>(eg:USD,INR,AUD,...)</span><br><br>
            <input type="submit" value="PREDICT">

        </form>
    </div>
</body>
</html>

app/templates/app/res.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Result sample</title>
    <link rel="icon" href="data:,">
    <style>
        table{
            border: 2px solid black;
        }
        td, tr{
            border: 1px solid black;
        }
    </style>
</head>
<body>
    <table>
        <tr>
            <th>Date</th>
            <th>Rate</th>
        </tr>
    {% for i,j in d.items %}
        <tr>
            <td>{{i}}</td>
            <td>{{j}}</td>
        </tr>
    {% endfor %}
    </table>
    <br>
    <a href="{% url 'app:graph' %}" target="_blank">Click here for the Graphical data</a>
</body>
</html>